from __future__ import annotations

from typing import Protocol

from docent.models import ChatMessage, RoomMessage, RoomState, TurnRequest, TurnResult


class RoomStore(Protocol):
    async def append(
        self,
        *,
        sender_id: str,
        sender_role: str,
        text: str,
        directed_recipient: str | None = None,
        idempotency_key: str | None = None,
    ) -> tuple[RoomMessage, bool]: ...
    async def get_by_idempotency_key(self, key: str) -> RoomMessage | None: ...

    async def messages_after(self, cursor: int, epoch: str | None) -> list[RoomMessage]: ...
    async def recent(self, limit: int) -> list[RoomMessage]: ...
    async def state(self, queued_turn_count: int) -> RoomState: ...
    async def reset(self) -> str: ...


class TurnQueue(Protocol):
    @property
    def maximum_size(self) -> int: ...
    async def enqueue(self, request: TurnRequest) -> bool: ...
    async def dequeue(self) -> TurnRequest | None: ...
    async def size(self) -> int: ...
    async def clear(self) -> None: ...


class AgentRuntime(Protocol):
    async def execute(self, request: TurnRequest) -> TurnResult: ...


class SessionStore(Protocol):
    async def get(self, session_id: str) -> list[ChatMessage]: ...
    async def append(self, session_id: str, message: ChatMessage) -> None: ...
    async def clear(self, session_id: str) -> None: ...
